@php
    $auditLogs = [
        [
            'id' => 1042,
            'user' => 'Admin User',
            'email' => 'admin@nadika.library',
            'action' => 'book.created',
            'description' => 'Created book "Atomic Habits" in catalog',
            'severity' => 'info',
            'ip' => '192.168.1.42',
            'browser' => 'Chrome 126',
            'device' => 'Desktop · macOS',
            'timestamp' => 'Jul 2, 2026 14:32:18',
            'relative' => '2 min ago',
        ],
        [
            'id' => 1041,
            'user' => 'Sarah Chen',
            'email' => 'sarah.chen@email.com',
            'action' => 'borrowing.returned',
            'description' => 'Returned "Design Patterns" — on time',
            'severity' => 'success',
            'ip' => '10.0.0.18',
            'browser' => 'Safari 17',
            'device' => 'Mobile · iOS',
            'timestamp' => 'Jul 2, 2026 14:15:04',
            'relative' => '19 min ago',
        ],
        [
            'id' => 1040,
            'user' => 'Michael Brown',
            'email' => 'michael.b@email.com',
            'action' => 'auth.login_failed',
            'description' => 'Failed login attempt — invalid password',
            'severity' => 'warning',
            'ip' => '203.45.67.89',
            'browser' => 'Firefox 128',
            'device' => 'Desktop · Windows',
            'timestamp' => 'Jul 2, 2026 13:58:41',
            'relative' => '36 min ago',
        ],
        [
            'id' => 1039,
            'user' => 'System',
            'email' => 'system@nadika.library',
            'action' => 'settings.updated',
            'description' => 'Fine rate changed from Rp 5,000 to Rp 7,500 per day',
            'severity' => 'info',
            'ip' => '127.0.0.1',
            'browser' => 'Internal',
            'device' => 'Server · Linux',
            'timestamp' => 'Jul 2, 2026 12:00:00',
            'relative' => '2 hours ago',
        ],
        [
            'id' => 1038,
            'user' => 'Admin User',
            'email' => 'admin@nadika.library',
            'action' => 'member.deleted',
            'description' => 'Permanently deleted member account #2847',
            'severity' => 'danger',
            'ip' => '192.168.1.42',
            'browser' => 'Chrome 126',
            'device' => 'Desktop · macOS',
            'timestamp' => 'Jul 2, 2026 11:22:33',
            'relative' => '3 hours ago',
        ],
        [
            'id' => 1037,
            'user' => 'John Mitchell',
            'email' => 'john.mitchell@email.com',
            'action' => 'borrowing.created',
            'description' => 'Borrowed "Clean Code" — due Jul 15, 2026',
            'severity' => 'success',
            'ip' => '172.16.0.55',
            'browser' => 'Edge 126',
            'device' => 'Tablet · Windows',
            'timestamp' => 'Jul 1, 2026 16:45:12',
            'relative' => '22 hours ago',
        ],
        [
            'id' => 1036,
            'user' => 'Emily Davis',
            'email' => 'emily.davis@email.com',
            'action' => 'auth.password_changed',
            'description' => 'Password changed successfully',
            'severity' => 'info',
            'ip' => '10.0.0.92',
            'browser' => 'Chrome 126',
            'device' => 'Mobile · Android',
            'timestamp' => 'Jul 1, 2026 09:10:27',
            'relative' => '1 day ago',
        ],
        [
            'id' => 1035,
            'user' => 'Unknown',
            'email' => '—',
            'action' => 'auth.brute_force',
            'description' => 'Multiple failed login attempts blocked (IP rate limit)',
            'severity' => 'danger',
            'ip' => '45.33.22.11',
            'browser' => 'Unknown',
            'device' => 'Unknown',
            'timestamp' => 'Jun 30, 2026 23:59:01',
            'relative' => '2 days ago',
        ],
    ];

    $severityVariants = [
        'info' => 'neutral',
        'success' => 'success',
        'warning' => 'warning',
        'danger' => 'danger',
    ];
@endphp
